explDict12 = {
 '1': {
  '2*US tax code 403 (b)': 'T',
  '3*US tax code 403 (b) eligibility': 'R',
 },
 '2': {
  '2*403(b) retirement plan': 'T',
  '3*personal IRA': 'R',
  '4*personal IRA v 403 (b)': 'R',
  '5*personal IRA or 403 (b)': 'T',
  '6*help retirement plan': 'R',
 },
 '3': {
  '2*teach yourself programming': 'T',
  '3*best programming language for beginners': 'R',
 },
 '4': {
  '2*pocono mountains region': 'T',
  '3*pocono mountains region things to do': 'R',
  '4*pocono mountains region activities': 'T',
  '5*pocono mountains region national park': 'R',
 },
 '5': {
  '2*pocono mountains': 'T',
  '3*pocono mountains park': 'R',
  '4*pocono mountains shopping': 'R',
 },
 '6': {
  '2*pocono mountains pennsylvania': 'T',
  '3*pocono mountains pennsylvania hotels': 'R',
  '4*pocono mountains pennsylvania things to do': 'R',
  '5*pocono mountains pennsylvania hotels': 'R',
  '6*pocono mountains camelbeach': 'R',
  '7*pocono mountains camelbeach hotel': 'T',
  '8*pocono mountains chateau resort': 'R',
  '9*pocono mountains chateau resort attractions': 'T',
  '10*pocono mountains chateau resort getting to': 'R',
  '11*chateau resort getting to': 'T',
  '12*pocono mountains chateau resort directions': 'T',
 },
 '7': {
  '2*pocono resort': 'T',
  '3*skytop lodge directions': 'R',
  '4*Philidelphia car rental': 'R',
 },
 '8': {
  '2*designer dogs': 'T',
  '3*designer dogs types': 'R',
 },
 '9': {
  '2*"designer dogs"': 'T',
  '3*"designer dogs" crossbreeds': 'R',
 },
 '10': {
  '2*designer dogs moral': 'T',
  '3*"designer" dogs': 'R',
 },
 '11': {
  '2*russian submarine Kursk sinks': 'T',
  '3*russian submarine Kursk fleet': 'R',
  '4*russian submarine Kursk on-board commander': 'R',
  '5*kursk commander': 'T',
  '6*kursk submarine commander': 'T',
  '7*kursk sink express regret': 'R',
  '8*kursk countries express regret': 'T',
  '9*kursk 2000 countries express regret': 'T',
  '10*kursk UK subs in area': 'R',
 },
 '12': {
  '2*Kursk russia today': 'T',
  '3*russiatoday.ru': 'T',
 },
 '13': {
  '2*kursk russian sinking': 'T',
  '3*kursk russian sinking US submarines': 'R',
 },
 '14': {
  '2*Kursk submarine 2000': 'T',
  '3*Kursk submarine 2000 politics': 'R',
 },
 '15': {
  '2*"russian politics" kursk submarine': 'T',
  '3*russia politics "kursk submarine"': 'T',
 },
 '16': {
  '2*Kursk   Barents see   Russian politics': 'T',
  '3*Kursk   Barents see   Russian politics   causes': 'R',
  '4*Kursk   Barents see   Russian politics   causes': 'T',
  '5*Kursk   Barents sea   causes': 'R',
 },
 '17': {
  '2*india government policy miss universe': 'T',
  '3*"indian government" policy miss universe': 'T',
 },
 '18': {
  '2*Indian politics   Miss Universe': 'T',
  '3*politics Indian Miss Universe': 'T',
  '4*politics 1994-2000  Indian Miss Universe': 'R',
 },
 '19': {
  '2*port arthur massacre': 'T',
  '3*port arthur massacre victims': 'R',
 },
 '20': {
  '2*port arthur': 'T',
  '3*port arthur massacre': 'T',
 },
 '21': {
  '2*Port Arther Massacre': 'T',
  '3*Port Arther Massacre Australia': 'T',
  '4*Port Arther Massacre Australia names died': 'R',
  '5*Port Arther Massacre Australia victims names': 'T',
 },
 '22': {
  '2*gun homicides australia': 'T',
  '3*martin bryant port arthur massacre': 'R',
  '4*port arthur massacre': 'T',
  '5*port arthur massacre australia': 'T',
  '6*gun homicides australia after 1996': 'R',
 },
 '23': {
  '2*port arthur martin bryant': 'T',
  '3*port arthur martin bryant gun crime': 'T',
 },
 '24': {
  '2*france world cup winners': 'T',
  '3*france 1998 final': 'T',
  '4*france vs brazil 1998 stadium': 'R',
 },
 '25': {
  '2*when france win world cuo': 'T',
  '3*when france win world cup': 'T',
  '4*france versus who world cup 1998': 'R',
  '5*france versus who world cup 1998 final score': 'T',
  '6*nickname for france football team in world cup 1998': 'R',
  '7*stadium final world cup 1998': 'R',
  '8*coach france football team world cup 1998': 'R',
 },
 '26': {
  '2*france world cup 1998': 'T',
  '3*france world cup 1998 reactions': 'R',
  '4*france world cup 1998 stock markets': 'R',
 },
 '27': {
  '2*stock market response to 1988 world cup': 'T',
  '3*stock market response to 1998 world cup': 'T',
  '4*french world cup 1998': 'R',
 },
 '28': {
  '2*france world cup 98 reaction stock market': 'T',
  '3*france world cup 98 reaction': 'R',
  '4*france world cup 98': 'R',
 },
 '29': {
  '2*bollywood': 'T',
  '3*bollywood stars': 'R',
  '4*bollywood beverly hills': 'R',
  '5*bollywood oscars': 'R',
  '6*world film industries': 'R',
 },
 '30': {
  '2*bollywood facts': 'T',
  '3*bollywood oscars': 'R',
 },
 '31': {
  '2*bollywood growth government policy': 'T',
  '3*bollywood legislation': 'R',
  '4*bollywood promote growth': 'R',
 },
 '32': {
  '2*bollywood legislation': 'T',
  '3*bollywood law': 'T',
 },
 '33': {
  '2*bollywood legislation growth': 'T',
  '3*bollywood legislation growth government': 'T',
 },
 '34': {
  '2*the company': 'T',
  '3*the company new york stock exchange': 'R',
 },
 '35': {
  '2*merck &amp;amp; co. lobbying': 'T',
  '3*merck &amp;amp; co. lobbying': 'T',
  '4*merck and co. lobbying': 'T',
  '5*merck and co': 'R',
  '6*merck and co policies': 'R',
 },
 '36': {
  '2*Merck lobby united states policy': 'T',
  '3*"Merck lobbyist" united states policy legislation': 'T',
  '4*merck lobbying': 'R',
 },
 '37': {
  '2*Merck lobbists': 'T',
  '3*Merck lobbying US policy': 'R',
 },
 '38': {
  '2*Kurosawa': 'T',
  '3*Kurosawa\'s wife': 'R',
 },
 '39': {
  '2*Akira Kurosawa influence': 'T',
  '3*Akira Kurosawa influence india': 'R',
  '4*"Akira Kurosawa" indian cinema': 'T',
  '5*"Akira Kurosawa" chinese cinema': 'R',
 },
 '40': {
  '2*water turbine efficiency': 'T',
  '3*water turbine cost per kwh': 'R',
 },
 '41': {
  '2*types of water turbines': 'T',
  '3*Newton\'s second law': 'R',
  '4*Newton\'s third law': 'R',
 },
 '42': {
  '2*water turbines': 'T',
  '3*water turbines relation to newtons law': 'R',
  '4*water turbines replace fossil fuels': 'R',
  '5*water turbines electricity generation cost per kWh': 'R',
  '6*effective water turbines types': 'R',
  '7*comparison of water turbine types': 'T',
 },
 '43': {
  '2*working mechanism of water turbines': 'T',
  '3*types of water turbines': 'R',
  '4*newtons laws on water turbines': 'R',
 },
 '44': {
  '2*hydropower renewable resource': 'T',
  '3*hydroelectric power': 'T',
  '4*hydroelectric power environment': 'R',
 },
 '45': {
  '2*consequences of hydroelectric dam': 'T',
  '3*hydropower efficiency': 'R',
 },
 '46': {
  '2*pseudocyesis': 'T',
  '3*pseudocyesis psychology': 'R',
 },
 '47': {
  '2*pseudocyesis': 'T',
  '3*pseudocyesis epidemiology': 'R',
  '4*pseudocyesis history': 'R',
 },
 '48': {
  '2*Pseudocyesis research': 'T',
  '3*Pseudocyesis causes research': 'T',
 },
 '49': {
  '2*Pseudoscyesis causes review': 'T',
  '3*Pseudoscyesis causes': 'T',
  '4*Pseudoscyesis': 'T',
 },
 '50': {
  '2*pseudocyesis': 'T',
  '3*pseudocyesis causes': 'T',
  '4*pseudocyesis causes new research': 'T',
  '5*causes of false preganancy': 'T',
 },
 '51': {
  '2*Pseudocyesis wiki': 'T',
  '3*Pseudocyesis pregnancy wiki': 'T',
 },
 '52': {
  '2*psuedocyesis': 'T',
  '3*psuedocyesis causes': 'T',
  '4*psuedocyesis causes research': 'T',
  '5*psuedocyesis causes study': 'T',
  '6*psuedocyesis pathogenesis': 'R',
  '7*psuedocyesis pathology': 'T',
 },
 '53': {
  '2*servering spinal cord paralysis': 'T',
  '3*servering spinal cord consequenses': 'R',
 },
 '54': {
  '2*"silicone roof coating" alternatives cooling': 'T',
  '3*"silicone roof coating" alternatives': 'T',
 },
 '55': {
  '2*silicone roof coating': 'T',
  '3*silicone roof coating uk': 'T',
  '4*silicone roof coating uk alternatives': 'R',
  '5*roof coating house temperature down uk': 'T',
 },
 '56': {
  '2*silicon roof coating': 'T',
  '3*silicon roof coating use': 'R',
  '4*silicon roof coating tutorial': 'T',
  '5*roof coating tutorial': 'T',
  '6*roof coating solutions': 'R',
  '7*roof coating lower temperature': 'R',
 },
 '57': {
  '2*self-regulating house temperature': 'T',
  '3*passive solar cooling': 'R',
  '4*passive solar cooling :uk': 'T',
  '5*radiant barrier': 'R',
  '6*radiant barrier :uk': 'T',
 },
 '58': {
  '2*install roof insulation': 'T',
  '3*how roof installation prevent heat': 'R',
 },
 '59': {
  '2*air condition roof': 'T',
  '3*cool roof': 'T',
 },
 '60': {
  '2*reduce airconditioning': 'T',
  '3*attic insulation airconditioning costs': 'R',
 },
 '61': {
  '2*Indian wedding culture rituals': 'T',
  '3*Indian wedding customs': 'T',
 },
 '62': {
  '2*Indian wedding rituals': 'T',
  '3*Indian wedding customs': 'T',
 },
 '63': {
  '2*wedding traditions buddhism': 'T',
  '3*buddhist wedding rituals': 'T',
  '4*shinto wedding rituals': 'R',
 },
 '64': {
  '2*Sunspots Wikipedia': 'T',
  '3*Sunspots Environmental effects': 'R',
  '4*Sunspot life cycle': 'R',
  '5*Are sunspots local burnouts': 'R',
  '6*How do sunspots effect us': 'R',
 },
 '65': {
  '2*sunspots climate changes': 'T',
  '3*sunspots affect climate changes': 'T',
 },
 '66': {
  '2*depression': 'T',
  '3*depression nhs': 'T',
 },
 '67': {
  '2*Depression Definition': 'T',
  '3*Depression Definition Merck Manual': 'R',
 },
 '68': {
  '2*depression symptoms treatment': 'T',
  '3*depression symptoms treatment nhs': 'T',
 },
 '69': {
  '2*depression diagnosis, sleep*, help, support': 'T',
  '3*depression diagnosis, sleep*, help, support, uk': 'T',
 },
 '70': {
  '2*depression symptoms': 'T',
  '3*how to help depressed person': 'R',
 },
 '71': {
  '2*dehumidifiers': 'T',
  '3*dehumidifiers things to condiser': 'T',
  '4*dehumidifiers things to consider': 'T',
  '5*dehumidifiers technical specifications': 'R',
  '6*dehumidifiers technical specifications uk': 'T',
 },
 '72': {
  '2*dehumidifier': 'T',
  '3*whole house dehumidifier': 'R',
 },
 '73': {
  '2*dehumidifiers': 'T',
  '3*dehumidifiers timer frost-free': 'R',
 },
 '74': {
  '2*dehumidifier comparison': 'T',
  '3*dehumidifier comparison UK': 'T',
  '4*dehumidifier comparison which?': 'T',
 },
 '75': {
  '2*dehumidifier comparison ratings': 'T',
  '3*dehumidifier comparison ratings uk': 'T',
 },
 '76': {
  '2*buy dehumidifier, reviews': 'T',
  '3*buy dehumidifier, reviews, uk': 'T',
 },
 '77': {
  '2*dehumidifier any good?': 'T',
  '3*dehumidifier any good? uk': 'T',
 },
 '78': {
  '2*Swahili dishes': 'T',
  '3*traditional Swahili dishes': 'T',
 },
 '79': {
  '2*swahili recipes': 'T',
  '3*traditional swahili recipes': 'T',
 },
 '80': {
  '2*swahili dish': 'T',
  '3*swahili dish kenya picture': 'R',
 },
 '81': {
  '2*recipes swahili cusine': 'T',
  '3*wikipedia kenya': 'R',
 },
 '82': {
  '2*Traditional Swahili meals': 'T',
  '3*Kenyan recipe': 'R',
 },
 '83': {
  '2*kenya cooking traditional': 'T',
  '3*kenya cooking traditional swahili': 'T',
  '4*www.allrecipes.com': 'R',
  '5*traditional swahili recipe': 'R',
 },
 '84': {
  '2*swahili traditional food recipes': 'T',
  '3*kenya swahili traditional food recipes': 'T',
 },
 '85': {
  '2*glass blowing': 'T',
  '3*glass blowing science': 'R',
  '4*scientific glass blowing': 'T',
 },
 '86': {
  '2*scientific glass blowing': 'T',
  '3*scientific glass blowing history': 'T',
  '4*glass blowing science': 'T',
 },
 '87': {
  '2*glassblowing history': 'T',
  '3*scientific glassblowing history': 'T',
  '4*scientific glassblowing history Edison': 'R',
 },
 '88': {
  '2*test tube sealing services': 'T',
  '3*hermetic sealing services': 'T',
 },
 '89': {
  '2*sample tube sealing': 'T',
  '3*sample tube sealing services': 'T',
  '4*sample tube sealing expert': 'R',
 },
 '90': {
  '2*collagen vascular diease': 'T',
  '3*collagen vascular diease sport': 'R',
  '4*autoimmune disease sport': 'R',
  '5*autoimmune disease': 'R',
 },
 '91': {
  '2*collagen vascular disease': 'T',
  '3*impact of collagen vascular disease': 'R',
  '4*collagen vascular disease active lifestyle': 'R',
  '5*collagen vascular disease sport': 'R',
  '6*"collagen vascular disease" sport': 'T',
  '7*"collagen vascular disease"': 'R',
 },
 '92': {
  '2*connecticut fire academy': 'T',
  '3*connecticut fire academy established': 'R',
  '4*"connecticut fire academy"': 'R',
 },
 '93': {
  '2*connecticut fire academy': 'T',
  '3*connecticut fire department': 'T',
  '4*connecticut fire academy': 'T',
 },
 '94': {
  '2*"connecticut fire academy"': 'T',
  '3*"connecticut fire academy" wiki': 'T',
  '4*"connecticut fire academy" fireman': 'R',
  '5*"Connecticut Fire Academy" fireman': 'T',
  '6*"Connecticut Fire Academy"': 'R',
 },
 '95': {
  '2*Connecticut Fire Academy': 'T',
  '3*what is the Connecticut Fire Academy?': 'T',
  '4*where is the Connecticut Fire Academy?': 'R',
 },
 '96': {
  '2*connecticut fire academy training': 'T',
  '3*connecticut fire academy': 'R',
 },
 '97': {
  '2*Connecticut Fire Academy training': 'T',
  '3*"Connecticut Fire Academy" training': 'T',
  '4*"Connecticut Fire Academy" skills': 'R',
 },
 '98': {
  '2*connecticut fire academy training': 'T',
  '3*"connecticut fire academy" training': 'T',
 }
}

explDict13 = {
 '1': {
  '2*US civil war causes': 'T',
  '3*US civil war economic  causes': 'R',
 },
 '2': {
  '2*scooter brands': 'T',
  '3*scooter brands reliable': 'R',
  '4*scooter': 'R',
  '5*scooter cheap': 'T',
  '6*scooter review': 'T',
  '7*scooter price': 'T',
  '8*scooter price': 'T',
  '9*scooter stores': 'R',
  '10*where to buy scooters': 'T',
 },
 '3': {
  '2*heart attack causes': 'T',
  '3*heart attack causes nhs': 'T',
  '4*heart attack causes site:nhs.uk': 'T',
 },
 '4': {
  '2*heart attack details': 'T',
  '3*heart attack': 'R',
  '4*heart attack statistics': 'R',
 },
 '5': {
  '2*heart attack': 'T',
  '3*heart attack treatment': 'R',
  '4*heart disease': 'R',
 },
 '6': {
  '2*long-term care insurance': 'T',
  '3*long term care insurance': 'T',
  '4*long term care insurance uk': 'R',
  '5*long term care insurance uk \\u00a3': 'T',
  '6*long term care insurance "united kingdom" OR britain OR england': 'T',
  '7*long term care insurance -usa': 'R',
 },
 '7': {
  '2*long-term care insurance': 'T',
  '3*long-term care insurance wiki': 'T',
  '4*define: long-term care insurance': 'T',
  '5*define: "long-term care insurance"': 'T',
  '6*long-term care insurance review': 'R',
  '7*long-term care insurance comparisons -job': 'T',
  '8*long-term care vs life insurance': 'R',
  '9*long-term care vs life insurance -job': 'T',
 },
 '8': {
  '2*us coinds': 'T',
  '3*us coins': 'T',
  '4*us coins wiki': 'T',
  '5*coins in us wiki': 'T',
 },
 '9': {
  '2*old us coins': 'T',
  '3*collecting old us coins': 'R',
  '4*selling old us coins': 'R',
  '5*selling old "usa coins"': 'T',
 },
 '10': {
  '2*quit smoking': 'T',
  '3*quit smoking cold turkey': 'R',
 },
 '11': {
  '2*how to quit smoking': 'T',
  '3*quiting smoking side effecs': 'R',
  '4*quiting smoking side effects': 'T',
  '5*quiting smoking using hypnosis': 'R',
  '6*quiting smoking help': 'R',
 },
 '12': {
  '2*wiki kansas city tourism': 'T',
  '3*kansas city hotels airport': 'R',
  '4*kansas city chiefs fixtures': 'R',
 },
 '13': {
  '2*kansas city MO': 'T',
  '3*kansas city airport hotels': 'R',
  '4*kansas city casino': 'R',
  '5*kansas city zoo': 'R',
  '6*kansas city state parks': 'R',
  '7*kansas city wikipedia': 'R',
  '8*kansas city history': 'R',
  '9*kansas city things to do': 'R',
 },
 '14': {
  '2*uk road trip idead': 'T',
  '3*uk road trip ideas': 'T',
  '4*what to take on a road trip': 'R',
  '5*what to take on a uk road trip': 'R',
 },
 '15': {
  '2*road trip FAQ': 'T',
  '3*planning a road trip': 'R',
 },
 '16': {
  '2*further education for high school teacher online funding': 'T',
  '3*training high school teacher free professional development': 'R',
 },
 '17': {
  '2*jp morgan data centers': 'T',
  '3*jp morgan data': 'T',
  '4*jp morgan data centers investment': 'R',
  '5*jp morgan largest data center': 'R',
  '6*data center compare microsoft jp morgan': 'R',
 },
 '18': {
  '2*JP Morgan Chase data centers': 'T',
  '3*JP Morgan Chase "data centers"': 'T',
  '4*location "JP Morgan Chase" "data centers"': 'R',
  '5*location "JP Morgan Chase" +"data centers"': 'T',
  '6*location "JP Morgan Chase" + center': 'T',
  '7*JP Morgan Chase overview': 'R',
  '8*JP Morgan Chase annual report': 'T',
  '9*"data centers"': 'R',
  '10*financial "data centers"': 'R',
 },
 '19': {
  '2*JP Morgan Chase data centres': 'T',
  '3*JP Morgan Chase data centres vs google': 'R',
  '4*JP Morgan Chase computational scientist profile': 'R',
  '5*JP Morgan computational scientist profile': 'T',
  '6*JP Morgan data center news': 'R',
 },
 '20': {
  '2*march madness': 'T',
  '3*march madness 2012 winning tean': 'R',
  '4*march madness 2012 winning team': 'T',
  '5*march madness 2012 runner up': 'R',
  '6*march madness 2012 host city': 'R',
  '7*march madness 2012 host stadium': 'R',
  '8*march madness 2012 final four': 'R',
  '9*march madness 2012 number teams': 'R',
  '10*march madness slang': 'R',
  '11*march madness slang expression': 'T',
  '12*march madness semi finals': 'R',
 },
 '21': {
  '2*"march madness"': 'T',
  '3*"march madness" NCAA': 'R',
  '4*"march madness"': 'R',
  '5*NCAA': 'R',
  '6*NCAA tournament': 'T',
  '7*NCAA tournament "march madness"': 'T',
  '8*NCAA tournament "march madness" wikipedia': 'T',
  '9*NCAA tournament "march madness" 2012 championship runner-up': 'R',
  '10*won NCAA "march madness" 2012': 'T',
  '11*NCAA "march madness" 2012 results': 'T',
  '12*NCAA "march madness" 2012 broadcast': 'R',
  '13*NCAA "march madness" 2012 semifinals sport news': 'R',
 },
 '22': {
  '2*face transplants wiki': 'T',
  '3*"Connie Culp"': 'R',
  '4*"Connie Culp" wikipedia': 'T',
  '5*"Connie Culp"': 'T',
  '6*First "Face Transplant"': 'R',
  '7*"Isabelle Dinoire"': 'R',
  '8*Isabelle Dinoire': 'T',
  '9*Isabelle Dino*': 'T',
  '10*Isabelle "face transplants"': 'T',
  '11*"Richard Norris"': 'R',
  '12*first "face transplant" surgery in the world': 'R',
  '13*first "full face transplant" Oscar': 'T',
  '14*first "full face transplant"': 'T',
 },
 '23': {
  '2*dulles airport': 'T',
  '3*dulles airport location': 'T',
  '4*dulles hotels': 'R',
  '5*dulles hotels': 'T',
  '6*dulles hotels': 'T',
  '7*dulles hotels': 'T',
  '8*dulles metro stop': 'R',
 },
 '24': {
  '2*where is dulles airport?': 'T',
  '3*dulles airport virginia': 'R',
  '4*dulles airport virginia transport to other cities': 'R',
 },
 '25': {
  '2*Boston pops  and (salary OR manager OR conductor OR hall)': 'T',
  '3*Boston pops': 'R',
 },
 '26': {
  '2*Boston Pops': 'T',
  '3*Define: Boston Pops': 'T',
  '4*Conductor of the boston pops orchestra': 'R',
  '5*Conductor 2012 of the boston pops orchestra': 'T',
  '6*Information regarding the Boston Pops Conductor': 'T',
  '7*Information regarding the Boston Pops Manager': 'R',
 },
 '27': {
  '2*jeopardy': 'T',
  '3*jeopardy gameplay': 'T',
  '4*jeopardy video': 'R',
 },
 '28': {
  '2*"jeopardy game show"': 'T',
  '3*"jeopardy game show" history': 'R',
 },
 '29': {
  '2*jeopardy (game show)': 'T',
  '3*jeopardy (game show) wikipedia': 'T',
  '4*wikipedia jeopardy': 'T',
 },
 '30': {
  '2*churchill downs': 'T',
  '3*churchill downs 2013': 'R',
 },
 '31': {
  '2*churchill downs racing information': 'T',
  '3*churchill downs horse racing park': 'R',
  '4*"churchill downs" horse racing park': 'T',
  '5*"churchill downs" horse racing schedule': 'T',
  '6*kentucky derby museum': 'R',
  '7*churchilldowns.com': 'R',
  '8*churchilldowns': 'T',
  '9*churchilldowns seating chart': 'R',
  '10*"churchill downs" racing seating chart': 'T',
 },
 '32': {
  '2*Churchill downs schedule': 'T',
  '3*Churchill downs race schedule 2013': 'T',
  '4*Churchill downs seating': 'R',
  '5*Churchill downs Kentucky derby museum': 'R',
 },
 '33': {
  '2*general schedule pay tables': 'T',
  '3*general schedule pay tables 2013': 'R',
  '4*general schedule pay tables federal wage system': 'R',
  '5*general schedule pay tables "federal goverment"': 'R',
 },
 '34': {
  '2*internet phone services': 'T',
  '3*internet phone services review': 'R',
  '4*guide internet phone services': 'T',
  '5*voip providers': 'R',
 },
 '35': {
  '2*regular phones vs internet phones voip experiences cheapest': 'T',
  '3*internet phones voip experiences cheapest': 'T',
  '4*internet phones voip reviews': 'R',
 },
 '36': {
  '2*VOIP': 'T',
  '3*VOIP lietuva': 'R',
  '4*VOIP paslaugos lietuva': 'T',
  '5*ip telefonijos paslaugos': 'R',
  '6*ip telefonija': 'T',
  '7*ip telefonija kaunas': 'T',
  '8*ip telefonas': 'R',
  '9*ip balso telefonija': 'R',
  '10*voip telefonas': 'R',
 },
 '37': {
  '2*"State university of new york" bioinformatics': 'T',
  '3*"State university of new york"': 'R',
 },
 '38': {
  '2*SUNY colleges': 'T',
  '3*SUNY albany hospital location': 'R',
  '4*"SUNY albany hospital" location': 'T',
  '5*"SUNY albany hospital" location': 'T',
  '6*albany university hospital location': 'T',
  '7*SUNY plattsburgh athletics': 'R',
 },
 '39': {
  '2*suny colleges names': 'T',
  '3*number of suny colleges': 'R',
  '4*suny college bioinformatics degree': 'R',
  '5*map suny albany hospital': 'R',
  '6*map "albany hospital" ny': 'T',
 },
 '40': {
  '2*gun control opinions': 'T',
  '3*gun control us government': 'R',
  '4*gun control current affairs': 'R',
  '5*gun control current affairs': 'T',
  '6*gun violence us': 'R',
  '7*law center to prevent gun violence': 'R',
 },
 '41': {
  '2*obama gun control': 'T',
  '3*gun control laws obama': 'T',
 },
 '42': {
  '2*most violent gun violence events': 'T',
  '3*gun violence us campuses': 'R',
  '4*most deadly type of gun in gun violence': 'R',
 },
 '43': {
  '2*gun violence in USA': 'T',
  '3*gun violence on US college campus': 'R',
  '4*gun violence on US campus': 'T',
  '5*types of gun used in violent events': 'R',
 },
 '44': {
  '2*healty recipes': 'T',
  '3*healthy meals': 'T',
  '4*healthy nutrition for infants': 'R',
 },
 '45': {
  '2*red bull drink health concerns': 'T',
  '3*red bull drink side effects ban': 'R',
  '4*red bull ban': 'T',
 },
 '46': {
  '2*Red Bull AND health': 'T',
  '3*Red Bull': 'R',
  '4*red bull': 'T',
  '5*red bull effects': 'R',
  '6*red bull drink': 'R',
  '7*red bull ingridients': 'R',
  '8*red bull ingredients': 'T',
  '9*red bull in US': 'R',
 },
 '47': {
  '2*banned drinks': 'T',
  '3*banned food': 'R',
  '4*illegal beverages': 'R',
 },
 '48': {
  '2*patent filing': 'T',
  '3*patent filing': 'T',
  '4*patent office': 'R',
  '5*patent law': 'R',
  '6*patent law uk': 'T',
  '7*patent lawyer': 'R',
  '8*provisional patent': 'R',
 },
 '49': {
  '2*face transplant': 'T',
  '3*finished the task': 'R',
 },
 '50': {
  '2*diet exercise for fitness': 'T',
  '3*fitness wiki': 'T',
  '4*wikipedia': 'R',
  '5*paleo diet': 'R',
  '6*keto diet': 'R',
  '7*keto diet wikipedia': 'T',
  '8*exercises for fitness': 'R',
  '9*how to get fit safely': 'R',
 },
 '51': {
  '2*fitness regime': 'T',
  '3*running a half marathon': 'R',
 },
 '52': {
  '2*venture capital': 'T',
  '3*loans for entrepreneurship': 'R',
  '4*loans for entrepreneurship switzerland': 'T',
  '5*loans for business': 'T',
  '6*loans for business us government': 'T',
  '7*renting a building business sillicon valley': 'R',
  '8*renting an office sillicon valley': 'T',
 },
 '53': {
  '2*how to get a pay raise': 'T',
  '3*tips pay raise': 'T',
  '4*tips pay raise': 'T',
 },
 '54': {
  '2*preventing employee fraud in recession': 'T',
  '3*recession employee fraud': 'T',
  '4*employee fraud best practice': 'T',
  '5*"employee fraud" "best practice"': 'T',
 },
 '55': {
  '2*employee evaluation': 'T',
  '3*evaluate employees': 'T',
  '4*evaluate employees': 'T',
 },
 '56': {
  '2*events ideas students community': 'T',
  '3*events ideas student association': 'T',
 },
 '57': {
  '2*developmental milestones infants': 'T',
  '3*developmental milestones infants 0-12 months': 'T',
  '4*developmental milestones infants east asia': 'R',
  '5*developmental milestones east asia': 'T',
  '6*"developmental milestones in east asia"': 'T',
  '7*developmental milestones asian infants': 'T',
  '8*asian infants': 'T',
  '9*asian infants milestones': 'T',
  '10*asian infants development': 'T',
  '11*asian babies development': 'T',
  '12*developmental milestones asia': 'T',
  '13*are developmental milestones universal': 'R',
  '14*asian developmental milestones': 'R',
  '15*chinese infant developmental milestones': 'R',
  '16*chinese infant milestones': 'T',
  '17*infant milestones variations': 'R',
  '18*infant milestones cultural': 'T',
  '19*infant milestones differences': 'T',
  '20*asian children milestones': 'R',
 },
 '58': {
  '2*policies for addressing economic problems in europe': 'T',
  '3*\'EUROPEAN UNION" "ECONOMIC CRISIS"': 'R',
  '4*\'EUROPEAN UNION" "ECONOMIC CRISIS" greece': 'R',
  '5*\'EUROPEAN UNION" "ECONOMIC CRISIS" portugal': 'R',
  '6*\'EUROPEAN UNION" "ECONOMIC CRISIS" spain': 'R',
 },
 '59': {
  '2*eurozone crisis responses': 'T',
  '3*eurozone crisis leader actions': 'R',
 },
 '60': {
  '2*eurozone portugal leader actions': 'T',
  '3*eurozone spain leader actions': 'R',
  '4*spain spanish leader crisis action': 'T',
  '5*ireland spanish leader crisis action': 'R',
  '6*ireland irish leader crisis action': 'T',
  '7*piigs leader crisis action': 'R',
  '8*cyprus leader crisis action': 'R',
 },
 '61': {
  '2*round-trip v road-trip': 'T',
  '3*round-trip advantages versus road-trip': 'R',
  '4*round-trip enjoyable versus road-trip': 'T',
  '5*round-trip enjoyable versus road-trip boring?': 'T',
 },
 '62': {
  '2*road trip': 'T',
  '3*best road trips': 'R',
  '4*best worst road trips': 'R',
  '5*romantic road trips': 'R',
  '6*enjoyable boring road trip': 'R',
  '7*enjoyable boring getaways': 'T',
  '8*best getaways': 'R',
 },
 '63': {
  '2*good internet phone services': 'T',
  '3*internet phone': 'T',
  '4*what\'s good about internet phoning': 'R',
  '5*"what\'s good about internet phoning"': 'T',
  '6*phone': 'R',
  '7*phone internet': 'R',
  '8*phone internet providers': 'T',
  '9*good Voip': 'R',
  '10*Voip reviews': 'T',
 },
 '64': {
  '2*why is internet phone service great': 'T',
  '3*why internet phone service great': 'T',
 },
 '65': {
  '2*gun control': 'T',
  '3*gun control laws': 'R',
  '4*gun control outcomes': 'R',
  '5*ban guns': 'R',
 },
 '66': {
  '2*gun control': 'T',
  '3*gun control violence': 'R',
  '4*does gun control reduce gun violence': 'R',
 },
 '67': {
  '2*god existence': 'T',
  '3*naturalism': 'R',
  '4*naturalism theory': 'T',
  '5*naturalism theism': 'T',
 },
 '68': {
  '2*US healthcare social security worker': 'T',
  '3*US healthcare system': 'T',
  '4*us healthcare for employed': 'T',
  '5*how does healthcare work in the USA for employed people?': 'T',
 },
 '69': {
  '2*malaria impact on economy africa': 'T',
  '3*malaria economy africa': 'T',
  '4*malaria economy': 'T',
  '5*malaria donations': 'R',
 },
 '70': {
  '2*HIV Africa charity medicine': 'T',
  '3*HIV Africa charity': 'T',
  '4*HIV Africa charity donate': 'R',
  '5*AIDS Africa charity donate': 'T',
  '6*malaria Africa charity donate': 'T',
 },
 '71': {
  '2*teachers evaluation': 'T',
  '3*teachers evaluation by students': 'R',
  '4*teachers evaluation students peers': 'R',
  '5*teachers evaluation peers': 'R',
  '6*teachers evaluation peers students': 'R',
  '7*teachers evaluation by students': 'R',
  '8*teachers evaluation': 'R',
  '9*teachers evaluation wikipedia': 'T',
  '10*teachers assement': 'T',
  '11*teachers evaluation': 'T',
  '12*teachers excellence': 'T',
  '13*teache assement wikipedia': 'T',
 },
 '72': {
  '2*infants development culture': 'T',
  '3*infant development "cultural effects"': 'T',
  '4*infant OR child development intitle:culture': 'T',
  '5*infant OR child development milestones': 'R',
  '6*infant OR child development milestones research': 'T',
  '7*infant OR child "development milestones" +research': 'T',
  '8*infant OR child "development milestones" site:ac.uk': 'T',
  '9*Do infants age 0-12 months experience different developmental milestones depending on culture': 'R',
  '10*culture OR race infant OR child development stages OR milestones': 'T',
  '11*research culture OR race infant OR child development stages OR milestones': 'T',
  '12*infant OR child development "effect of culture"': 'T',
  '13*infant OR child development "cultural differences"': 'T',
  '14*"child development" "cultural differences"': 'T',
 },
 '73': {
  '2*babies development "cultural differences"': 'T',
  '3*infant different developmental milestones depending on culture': 'T',
  '4*developmental milestones infants "cultural differences"': 'T',
 },
 '74': {
  '2*infant development cultural differences': 'T',
  '3*infant development western eastern cultures': 'R',
  '4*infant development milestone cultural effects': 'T',
  '5*infant development milestone "cultural differences"': 'T',
  '6*infant development milestone "cultural competence': 'T',
  '7*infant development milestone developed and third world countries': 'R',
 },
 '75': {
  '2*legality alcohol marijuana': 'T',
  '3*legality alcohol marijuana history': 'T',
  '4*legality alcohol history': 'T',
  '5*legality alcohol history maijuana': 'T',
  '6*legality alcohol history marijuana': 'T',
  '7*why is marijuana illegal?': 'R',
  '8*is marijuana worse for your health than alcohol?': 'R',
 },
 '76': {
  '2*phone plan': 'T',
  '3*"cell phone plan"': 'T',
  '4*"cell phone plan :.uk"': 'R',
 },
 '77': {
  '2*tax junk food benefits': 'T',
  '3*tax junk food benefits un': 'R',
  '4*tax junk food benefits UN evidence': 'T',
  '5*high calorie food tax evidence based': 'R',
  '6*high calorie snack tax evidence based': 'T',
  '7*government intervention tax "junk food"': 'T',
 },
 '78': {
  '2*advantages of junk food': 'T',
  '3*tax on junk food': 'R',
 },
 '79': {
  '2*food tax': 'T',
  '3*food ban': 'R',
 },
 '80': {
  '2*the benefits of exploration space': 'T',
  '3*the benefits of "exploration space"': 'T',
 },
 '81': {
  '2*women  and minorities percentage setting': 'T',
  '3*should numbers of women and minorities in workplace be contolled': 'R',
 },
 '82': {
  '2*jobs from business phds': 'T',
  '3*business phd': 'R',
 },
 '83': {
  '2*phd business jobs': 'T',
  '3*phd business salaries': 'R',
  '4*business phd funding': 'R',
  '5*business phd vs masters': 'R',
  '6*business phd duration': 'R',
  '7*business phd income': 'R',
 },
 '84': {
  '2*travel spots room prices': 'T',
  '3*travel spots room prices hawaii': 'R',
 },
 '85': {
  '2*Secondhand camera shop': 'T',
  '3*Travel information Los Angeles': 'R',
  '4*Local Travel information Los Angeles': 'T',
  '5*Travel information Los Angeles': 'T',
 },
 '86': {
  '2*New York City': 'T',
  '3*Chicago': 'R',
  '4*Washington DC': 'R',
 },
 '87': {
  '2*best us destinations': 'T',
  '3*distance new york boston': 'R',
  '4*maps.bing.com': 'R',
  '5*maps': 'T',
  '6*bing maps': 'T',
  '7*hartford tourism': 'R',
  '8*bing maps': 'R',
  '9*hartford visitors': 'T',
  '10*hartford connecticut tourism': 'T',
  '11*hartford boston travel': 'R',
  '12*boston tourism': 'T',
  '13*nyc tourism': 'R',
  '14*philadelphia nyc distance': 'R',
  '15*bing maps': 'R',
  '16*philadelphia washington dc distance': 'T',
  '17*bing maps': 'R',
  '18*philadelphia tourism': 'T',
  '19*washington dc tourism': 'R',
  '20*philadelphia nyc travel': 'R',
  '21*philadelphia nyc train': 'T',
  '22*philadelphia nyc bus': 'T',
 },
 '88': {
  '2*scooter comparison': 'T',
 },
 '89': {
  '2*ron howard filmography': 'T',
 },
 '90': {
  '2*Ron Howard, movies': 'T',
 },
 '91': {
  '2*paralegal career': 'T',
 },
 '92': {
  '2*weatherstripping': 'T',
 },
 '93': {
  '2*+(Black OR african-american) history month events': 'T',
 },
 '94': {
  '2*Black history month': 'T',
 },
 '95': {
  '2*comparison hotels new york city': 'T',
 },
 '96': {
  '2*American Coins': 'T',
 },
 '97': {
  '2*methods and programs for quitting smoking': 'T',
 },
 '98': {
  '2*quit quitting smoking': 'T',
 },
 '99': {
  '2*Kansas attractions': 'T',
 },
 '100': {
  '2*further education for high school teachers': 'T',
 },
 '101': {
  '2*higher degrees for high school teacher': 'T',
 },
 '102': {
  '2*jp morgan chase data centers': 'T',
 },
 '103': {
  '2*"history of face transplants"': 'T',
 },
 '104': {
  '2*AMT tax IRS': 'T',
 },
 '105': {
  '2*uss abraham lincoln': 'T',
 },
 '106': {
  '2*guide dulles airport': 'T',
 },
 '107': {
  '2*Dulles airport': 'T',
 },
 '108': {
  '2*Boston pops official website': 'T',
 },
 '109': {
  '2*GS pay tables': 'T',
 },
 '110': {
  '2*Vanuatu': 'T',
 },
 '111': {
  '2*healthy nutrition, children, pregnant women, government programes': 'T',
 },
 '112': {
  '2*patent application': 'T',
 },
 '113': {
  '2*face transplants': 'T',
 },
 '114': {
  '2*face transplants': 'T',
 },
 '115': {
  '2*advice for technology start-up': 'T',
 },
 '116': {
  '2*how to succeed in new venture': 'T',
 },
 '117': {
  '2*innovation': 'T',
 },
 '118': {
  '2*evaluating employees': 'T',
 },
 '119': {
  '2*eurozone crisis economic actions': 'T',
 },
 '120': {
  '2*Philadelphia attractions': 'T',
 },
 '121': {
  '2*Philadelphia tourist attractions': 'T',
 },
 '122': {
  '2*tour bus': 'T',
 },
 '123': {
  '2*legality gun control': 'T',
 },
 '124': {
  '2*god does not exist': 'T',
 },
 '125': {
  '2*existence god naturalism theory': 'T',
 },
 '126': {
  '2*hiv aids prevention cure charities in africa': 'T',
 },
 '127': {
  '2*teacher evaluation peer versus students': 'T',
 },
 '128': {
  '2*EU economic indicators': 'T',
 },
 '129': {
  '2*What are the effects of the ongoing Eurozone crisis on national economic indicators such as unemployment, GDP, public debt, etc': 'T',
 },
 '130': {
  '2*Jp Morgan Chase': 'T',
 },
 '131': {
  '2*us space exploration costs': 'T',
 },
 '132': {
  '2*(euro OR eurozone) crisis': 'T',
 },
 '133': {
  '2*eurozone crisis': 'T',
 }
}
