explDict12 = {
 '1': {
  '1*US tax code 403 (b)': 'T',
  '2*US tax code 403 (b) eligibility': 'R',
 },
 '2': {
  '1*403(b) retirement plan': 'T',
  '2*personal IRA': 'R',
  '3*personal IRA v 403 (b)': 'R',
  '4*personal IRA or 403 (b)': 'T',
  '5*help retirement plan': 'R',
 },
 '3': {
  '1*teach yourself programming': 'T',
  '2*best programming language for beginners': 'R',
 },
 '4': {
  '1*pocono mountains region': 'T',
  '2*pocono mountains region things to do': 'R',
  '3*pocono mountains region activities': 'T',
  '4*pocono mountains region national park': 'R',
 },
 '5': {
  '1*pocono mountains': 'T',
  '2*pocono mountains park': 'R',
  '3*pocono mountains shopping': 'R',
 },
 '6': {
  '1*pocono mountains pennsylvania': 'T',
  '2*pocono mountains pennsylvania hotels': 'R',
  '3*pocono mountains pennsylvania things to do': 'R',
  '4*pocono mountains pennsylvania hotels': 'R',
  '5*pocono mountains camelbeach': 'R',
  '6*pocono mountains camelbeach hotel': 'T',
  '7*pocono mountains chateau resort': 'R',
  '8*pocono mountains chateau resort attractions': 'T',
  '9*pocono mountains chateau resort getting to': 'R',
  '10*chateau resort getting to': 'T',
  '11*pocono mountains chateau resort directions': 'T',
 },
 '7': {
  '1*pocono resort': 'T',
  '2*skytop lodge directions': 'R',
  '3*Philidelphia car rental': 'R',
 },
 '8': {
  '1*designer dogs': 'T',
  '2*designer dogs types': 'R',
 },
 '9': {
  '1*"designer dogs"': 'T',
  '2*"designer dogs" crossbreeds': 'R',
 },
 '10': {
  '1*designer dogs moral': 'T',
  '2*"designer" dogs': 'R',
 },
 '11': {
  '1*russian submarine Kursk sinks': 'T',
  '2*russian submarine Kursk fleet': 'R',
  '3*russian submarine Kursk on-board commander': 'R',
  '4*kursk commander': 'T',
  '5*kursk submarine commander': 'T',
  '6*kursk sink express regret': 'R',
  '7*kursk countries express regret': 'T',
  '8*kursk 2000 countries express regret': 'T',
  '9*kursk UK subs in area': 'R',
 },
 '12': {
  '1*Kursk russia today': 'T',
  '2*russiatoday.ru': 'T',
 },
 '13': {
  '1*kursk russian sinking': 'T',
  '2*kursk russian sinking US submarines': 'R',
 },
 '14': {
  '1*Kursk submarine 2000': 'T',
  '2*Kursk submarine 2000 politics': 'R',
 },
 '15': {
  '1*"russian politics" kursk submarine': 'T',
  '2*russia politics "kursk submarine"': 'T',
 },
 '16': {
  '1*Kursk   Barents see   Russian politics': 'T',
  '2*Kursk   Barents see   Russian politics   causes': 'R',
  '3*Kursk   Barents see   Russian politics   causes': 'T',
  '4*Kursk   Barents sea   causes': 'R',
 },
 '17': {
  '1*india government policy miss universe': 'T',
  '2*"indian government" policy miss universe': 'T',
 },
 '18': {
  '1*Indian politics   Miss Universe': 'T',
  '2*politics Indian Miss Universe': 'T',
  '3*politics 1994-2000  Indian Miss Universe': 'R',
 },
 '19': {
  '1*port arthur massacre': 'T',
  '2*port arthur massacre victims': 'R',
 },
 '20': {
  '1*port arthur': 'T',
  '2*port arthur massacre': 'T',
 },
 '21': {
  '1*Port Arther Massacre': 'T',
  '2*Port Arther Massacre Australia': 'T',
  '3*Port Arther Massacre Australia names died': 'R',
  '4*Port Arther Massacre Australia victims names': 'T',
 },
 '22': {
  '1*gun homicides australia': 'T',
  '2*martin bryant port arthur massacre': 'R',
  '3*port arthur massacre': 'T',
  '4*port arthur massacre australia': 'T',
  '5*gun homicides australia after 1996': 'R',
 },
 '23': {
  '1*port arthur martin bryant': 'T',
  '2*port arthur martin bryant gun crime': 'T',
 },
 '24': {
  '1*france world cup winners': 'T',
  '2*france 1998 final': 'T',
  '3*france vs brazil 1998 stadium': 'R',
 },
 '25': {
  '1*when france win world cuo': 'T',
  '2*when france win world cup': 'T',
  '3*france versus who world cup 1998': 'R',
  '4*france versus who world cup 1998 final score': 'T',
  '5*nickname for france football team in world cup 1998': 'R',
  '6*stadium final world cup 1998': 'R',
  '7*coach france football team world cup 1998': 'R',
 },
 '26': {
  '1*france world cup 1998': 'T',
  '2*france world cup 1998 reactions': 'R',
  '3*france world cup 1998 stock markets': 'R',
 },
 '27': {
  '1*stock market response to 1988 world cup': 'T',
  '2*stock market response to 1998 world cup': 'T',
  '3*french world cup 1998': 'R',
 },
 '28': {
  '1*france world cup 98 reaction stock market': 'T',
  '2*france world cup 98 reaction': 'R',
  '3*france world cup 98': 'R',
 },
 '29': {
  '1*bollywood': 'T',
  '2*bollywood stars': 'R',
  '3*bollywood beverly hills': 'R',
  '4*bollywood oscars': 'R',
  '5*world film industries': 'R',
 },
 '30': {
  '1*bollywood facts': 'T',
  '2*bollywood oscars': 'R',
 },
 '31': {
  '1*bollywood growth government policy': 'T',
  '2*bollywood legislation': 'R',
  '3*bollywood promote growth': 'R',
 },
 '32': {
  '1*bollywood legislation': 'T',
  '2*bollywood law': 'T',
 },
 '33': {
  '1*bollywood legislation growth': 'T',
  '2*bollywood legislation growth government': 'T',
 },
 '34': {
  '1*the company': 'T',
  '2*the company new york stock exchange': 'R',
 },
 '35': {
  '1*merck &amp; co. lobbying': 'T',
  '2*merck &amp; co. lobbying': 'T',
  '3*merck and co. lobbying': 'T',
  '4*merck and co': 'R',
  '5*merck and co policies': 'R',
 },
 '36': {
  '1*Merck lobby united states policy': 'T',
  '2*"Merck lobbyist" united states policy legislation': 'T',
  '3*merck lobbying': 'R',
 },
 '37': {
  '1*Merck lobbists': 'T',
  '2*Merck lobbying US policy': 'R',
 },
 '38': {
  '1*Kurosawa': 'T',
  '2*Kurosawa\'s wife': 'R',
 },
 '39': {
  '1*Akira Kurosawa influence': 'T',
  '2*Akira Kurosawa influence india': 'R',
  '3*"Akira Kurosawa" indian cinema': 'T',
  '4*"Akira Kurosawa" chinese cinema': 'R',
 },
 '40': {
  '1*water turbine efficiency': 'T',
  '2*water turbine cost per kwh': 'R',
 },
 '41': {
  '1*types of water turbines': 'T',
  '2*Newton\'s second law': 'R',
  '3*Newton\'s third law': 'R',
 },
 '42': {
  '1*water turbines': 'T',
  '2*water turbines relation to newtons law': 'R',
  '3*water turbines replace fossil fuels': 'R',
  '4*water turbines electricity generation cost per kWh': 'R',
  '5*effective water turbines types': 'R',
  '6*comparison of water turbine types': 'T',
 },
 '43': {
  '1*working mechanism of water turbines': 'T',
  '2*types of water turbines': 'R',
  '3*newtons laws on water turbines': 'R',
 },
 '44': {
  '1*hydropower renewable resource': 'T',
  '2*hydroelectric power': 'T',
  '3*hydroelectric power environment': 'R',
 },
 '45': {
  '1*consequences of hydroelectric dam': 'T',
  '2*hydropower efficiency': 'R',
 },
 '46': {
  '1*pseudocyesis': 'T',
  '2*pseudocyesis psychology': 'R',
 },
 '47': {
  '1*pseudocyesis': 'T',
  '2*pseudocyesis epidemiology': 'R',
  '3*pseudocyesis history': 'R',
 },
 '48': {
  '1*Pseudocyesis research': 'T',
  '2*Pseudocyesis causes research': 'T',
 },
 '49': {
  '1*Pseudoscyesis causes review': 'T',
  '2*Pseudoscyesis causes': 'T',
  '3*Pseudoscyesis': 'T',
 },
 '50': {
  '1*pseudocyesis': 'T',
  '2*pseudocyesis causes': 'T',
  '3*pseudocyesis causes new research': 'T',
  '4*causes of false preganancy': 'T',
 },
 '51': {
  '1*Pseudocyesis wiki': 'T',
  '2*Pseudocyesis pregnancy wiki': 'T',
 },
 '52': {
  '1*psuedocyesis': 'T',
  '2*psuedocyesis causes': 'T',
  '3*psuedocyesis causes research': 'T',
  '4*psuedocyesis causes study': 'T',
  '5*psuedocyesis pathogenesis': 'R',
  '6*psuedocyesis pathology': 'T',
 },
 '53': {
  '1*servering spinal cord paralysis': 'T',
  '2*servering spinal cord consequenses': 'R',
 },
 '54': {
  '1*"silicone roof coating" alternatives cooling': 'T',
  '2*"silicone roof coating" alternatives': 'T',
 },
 '55': {
  '1*silicone roof coating': 'T',
  '2*silicone roof coating uk': 'T',
  '3*silicone roof coating uk alternatives': 'R',
  '4*roof coating house temperature down uk': 'T',
 },
 '56': {
  '1*silicon roof coating': 'T',
  '2*silicon roof coating use': 'R',
  '3*silicon roof coating tutorial': 'T',
  '4*roof coating tutorial': 'T',
  '5*roof coating solutions': 'R',
  '6*roof coating lower temperature': 'R',
 },
 '57': {
  '1*self-regulating house temperature': 'T',
  '2*passive solar cooling': 'R',
  '3*passive solar cooling :uk': 'T',
  '4*radiant barrier': 'R',
  '5*radiant barrier :uk': 'T',
 },
 '58': {
  '1*install roof insulation': 'T',
  '2*how roof installation prevent heat': 'R',
 },
 '59': {
  '1*air condition roof': 'T',
  '2*cool roof': 'T',
 },
 '60': {
  '1*reduce airconditioning': 'T',
  '2*attic insulation airconditioning costs': 'R',
 },
 '61': {
  '1*Indian wedding culture rituals': 'T',
  '2*Indian wedding customs': 'T',
 },
 '62': {
  '1*Indian wedding rituals': 'T',
  '2*Indian wedding customs': 'T',
 },
 '63': {
  '1*wedding traditions buddhism': 'T',
  '2*buddhist wedding rituals': 'T',
  '3*shinto wedding rituals': 'R',
 },
 '64': {
  '1*Sunspots Wikipedia': 'T',
  '2*Sunspots Environmental effects': 'R',
  '3*Sunspot life cycle': 'R',
  '4*Are sunspots local burnouts': 'R',
  '5*How do sunspots effect us': 'R',
 },
 '65': {
  '1*sunspots climate changes': 'T',
  '2*sunspots affect climate changes': 'T',
 },
 '66': {
  '1*depression': 'T',
  '2*depression nhs': 'T',
 },
 '67': {
  '1*Depression Definition': 'T',
  '2*Depression Definition Merck Manual': 'R',
 },
 '68': {
  '1*depression symptoms treatment': 'T',
  '2*depression symptoms treatment nhs': 'T',
 },
 '69': {
  '1*depression diagnosis, sleep*, help, support': 'T',
  '2*depression diagnosis, sleep*, help, support, uk': 'T',
 },
 '70': {
  '1*depression symptoms': 'T',
  '2*how to help depressed person': 'R',
 },
 '71': {
  '1*dehumidifiers': 'T',
  '2*dehumidifiers things to condiser': 'T',
  '3*dehumidifiers things to consider': 'T',
  '4*dehumidifiers technical specifications': 'R',
  '5*dehumidifiers technical specifications uk': 'T',
 },
 '72': {
  '1*dehumidifier': 'T',
  '2*whole house dehumidifier': 'R',
 },
 '73': {
  '1*dehumidifiers': 'T',
  '2*dehumidifiers timer frost-free': 'R',
 },
 '74': {
  '1*dehumidifier comparison': 'T',
  '2*dehumidifier comparison UK': 'T',
  '3*dehumidifier comparison which?': 'T',
 },
 '75': {
  '1*dehumidifier comparison ratings': 'T',
  '2*dehumidifier comparison ratings uk': 'T',
 },
 '76': {
  '1*buy dehumidifier, reviews': 'T',
  '2*buy dehumidifier, reviews, uk': 'T',
 },
 '77': {
  '1*dehumidifier any good?': 'T',
  '2*dehumidifier any good? uk': 'T',
 },
 '78': {
  '1*Swahili dishes': 'T',
  '2*traditional Swahili dishes': 'T',
 },
 '79': {
  '1*swahili recipes': 'T',
  '2*traditional swahili recipes': 'T',
 },
 '80': {
  '1*swahili dish': 'T',
  '2*swahili dish kenya picture': 'R',
 },
 '81': {
  '1*recipes swahili cusine': 'T',
  '2*wikipedia kenya': 'R',
 },
 '82': {
  '1*Traditional Swahili meals': 'T',
  '2*Kenyan recipe': 'R',
 },
 '83': {
  '1*kenya cooking traditional': 'T',
  '2*kenya cooking traditional swahili': 'T',
  '3*www.allrecipes.com': 'R',
  '4*traditional swahili recipe': 'R',
 },
 '84': {
  '1*swahili traditional food recipes': 'T',
  '2*kenya swahili traditional food recipes': 'T',
 },
 '85': {
  '1*glass blowing': 'T',
  '2*glass blowing science': 'R',
  '3*scientific glass blowing': 'T',
 },
 '86': {
  '1*scientific glass blowing': 'T',
  '2*scientific glass blowing history': 'T',
  '3*glass blowing science': 'T',
 },
 '87': {
  '1*glassblowing history': 'T',
  '2*scientific glassblowing history': 'T',
  '3*scientific glassblowing history Edison': 'R',
 },
 '88': {
  '1*test tube sealing services': 'T',
  '2*hermetic sealing services': 'T',
 },
 '89': {
  '1*sample tube sealing': 'T',
  '2*sample tube sealing services': 'T',
  '3*sample tube sealing expert': 'R',
 },
 '90': {
  '1*collagen vascular diease': 'T',
  '2*collagen vascular diease sport': 'R',
  '3*autoimmune disease sport': 'R',
  '4*autoimmune disease': 'R',
 },
 '91': {
  '1*collagen vascular disease': 'T',
  '2*impact of collagen vascular disease': 'R',
  '3*collagen vascular disease active lifestyle': 'R',
  '4*collagen vascular disease sport': 'R',
  '5*"collagen vascular disease" sport': 'T',
  '6*"collagen vascular disease"': 'R',
 },
 '92': {
  '1*connecticut fire academy': 'T',
  '2*connecticut fire academy established': 'R',
  '3*"connecticut fire academy"': 'R',
 },
 '93': {
  '1*connecticut fire academy': 'T',
  '2*connecticut fire department': 'T',
  '3*connecticut fire academy': 'T',
 },
 '94': {
  '1*"connecticut fire academy"': 'T',
  '2*"connecticut fire academy" wiki': 'T',
  '3*"connecticut fire academy" fireman': 'R',
  '4*"Connecticut Fire Academy" fireman': 'T',
  '5*"Connecticut Fire Academy"': 'R',
 },
 '95': {
  '1*Connecticut Fire Academy': 'T',
  '2*what is the Connecticut Fire Academy?': 'T',
  '3*where is the Connecticut Fire Academy?': 'R',
 },
 '96': {
  '1*connecticut fire academy training': 'T',
  '2*connecticut fire academy': 'R',
 },
 '97': {
  '1*Connecticut Fire Academy training': 'T',
  '2*"Connecticut Fire Academy" training': 'T',
  '3*"Connecticut Fire Academy" skills': 'R',
 },
 '98': {
  '1*connecticut fire academy training': 'T',
  '2*"connecticut fire academy" training': 'T',
 }
}

explDict13 = {
 '1': {
  '1*US civil war causes': 'T',
  '2*US civil war economic  causes': 'R',
 },
 '2': {
  '1*scooter brands': 'T',
  '2*scooter brands reliable': 'R',
  '3*scooter': 'R',
  '4*scooter cheap': 'T',
  '5*scooter review': 'T',
  '6*scooter price': 'T',
  '7*scooter price': 'T',
  '8*scooter stores': 'R',
  '9*where to buy scooters': 'T',
 },
 '3': {
  '1*heart attack causes': 'T',
  '2*heart attack causes nhs': 'T',
  '3*heart attack causes site:nhs.uk': 'T',
 },
 '4': {
  '1*heart attack details': 'T',
  '2*heart attack': 'R',
  '3*heart attack statistics': 'R',
 },
 '5': {
  '1*heart attack': 'T',
  '2*heart attack treatment': 'R',
  '3*heart disease': 'R',
 },
 '6': {
  '1*long-term care insurance': 'T',
  '2*long term care insurance': 'T',
  '3*long term care insurance uk': 'R',
  '4*long term care insurance uk \\u00a3': 'T',
  '5*long term care insurance "united kingdom" OR britain OR england': 'T',
  '6*long term care insurance -usa': 'R',
 },
 '7': {
  '1*long-term care insurance': 'T',
  '2*long-term care insurance wiki': 'T',
  '3*define: long-term care insurance': 'T',
  '4*define: "long-term care insurance"': 'T',
  '5*long-term care insurance review': 'R',
  '6*long-term care insurance comparisons -job': 'T',
  '7*long-term care vs life insurance': 'R',
  '8*long-term care vs life insurance -job': 'T',
 },
 '8': {
  '1*us coinds': 'T',
  '2*us coins': 'T',
  '3*us coins wiki': 'T',
  '4*coins in us wiki': 'T',
 },
 '9': {
  '1*old us coins': 'T',
  '2*collecting old us coins': 'R',
  '3*selling old us coins': 'R',
  '4*selling old "usa coins"': 'T',
 },
 '10': {
  '1*quit smoking': 'T',
  '2*quit smoking cold turkey': 'R',
 },
 '11': {
  '1*how to quit smoking': 'T',
  '2*quiting smoking side effecs': 'R',
  '3*quiting smoking side effects': 'T',
  '4*quiting smoking using hypnosis': 'R',
  '5*quiting smoking help': 'R',
 },
 '12': {
  '1*wiki kansas city tourism': 'T',
  '2*kansas city hotels airport': 'R',
  '3*kansas city chiefs fixtures': 'R',
 },
 '13': {
  '1*kansas city MO': 'T',
  '2*kansas city airport hotels': 'R',
  '3*kansas city casino': 'R',
  '4*kansas city zoo': 'R',
  '5*kansas city state parks': 'R',
  '6*kansas city wikipedia': 'R',
  '7*kansas city history': 'R',
  '8*kansas city things to do': 'R',
 },
 '14': {
  '1*uk road trip idead': 'T',
  '2*uk road trip ideas': 'T',
  '3*what to take on a road trip': 'R',
  '4*what to take on a uk road trip': 'R',
 },
 '15': {
  '1*road trip FAQ': 'T',
  '2*planning a road trip': 'R',
 },
 '16': {
  '1*further education for high school teacher online funding': 'T',
  '2*training high school teacher free professional development': 'R',
 },
 '17': {
  '1*jp morgan data centers': 'T',
  '2*jp morgan data': 'T',
  '3*jp morgan data centers investment': 'R',
  '4*jp morgan largest data center': 'R',
  '5*data center compare microsoft jp morgan': 'R',
 },
 '18': {
  '1*JP Morgan Chase data centers': 'T',
  '2*JP Morgan Chase "data centers"': 'T',
  '3*location "JP Morgan Chase" "data centers"': 'R',
  '4*location "JP Morgan Chase" +"data centers"': 'T',
  '5*location "JP Morgan Chase" + center': 'T',
  '6*JP Morgan Chase overview': 'R',
  '7*JP Morgan Chase annual report': 'T',
  '8*"data centers"': 'R',
  '9*financial "data centers"': 'R',
 },
 '19': {
  '1*JP Morgan Chase data centres': 'T',
  '2*JP Morgan Chase data centres vs google': 'R',
  '3*JP Morgan Chase computational scientist profile': 'R',
  '4*JP Morgan computational scientist profile': 'T',
  '5*JP Morgan data center news': 'R',
 },
 '20': {
  '1*march madness': 'T',
  '2*march madness 2012 winning tean': 'R',
  '3*march madness 2012 winning team': 'T',
  '4*march madness 2012 runner up': 'R',
  '5*march madness 2012 host city': 'R',
  '6*march madness 2012 host stadium': 'R',
  '7*march madness 2012 final four': 'R',
  '8*march madness 2012 number teams': 'R',
  '9*march madness slang': 'R',
  '10*march madness slang expression': 'T',
  '11*march madness semi finals': 'R',
 },
 '21': {
  '1*"march madness"': 'T',
  '2*"march madness" NCAA': 'R',
  '3*"march madness"': 'R',
  '4*NCAA': 'R',
  '5*NCAA tournament': 'T',
  '6*NCAA tournament "march madness"': 'T',
  '7*NCAA tournament "march madness" wikipedia': 'T',
  '8*NCAA tournament "march madness" 2012 championship runner-up': 'R',
  '9*won NCAA "march madness" 2012': 'T',
  '10*NCAA "march madness" 2012 results': 'T',
  '11*NCAA "march madness" 2012 broadcast': 'R',
  '12*NCAA "march madness" 2012 semifinals sport news': 'R',
 },
 '22': {
  '1*face transplants wiki': 'T',
  '2*"Connie Culp"': 'R',
  '3*"Connie Culp" wikipedia': 'T',
  '4*"Connie Culp"': 'T',
  '5*First "Face Transplant"': 'R',
  '6*"Isabelle Dinoire"': 'R',
  '7*Isabelle Dinoire': 'T',
  '8*Isabelle Dino*': 'T',
  '9*Isabelle "face transplants"': 'T',
  '10*"Richard Norris"': 'R',
  '11*first "face transplant" surgery in the world': 'R',
  '12*first "full face transplant" Oscar': 'T',
  '13*first "full face transplant"': 'T',
 },
 '23': {
  '1*dulles airport': 'T',
  '2*dulles airport location': 'T',
  '3*dulles hotels': 'R',
  '4*dulles hotels': 'T',
  '5*dulles hotels': 'T',
  '6*dulles hotels': 'T',
  '7*dulles metro stop': 'R',
 },
 '24': {
  '1*where is dulles airport?': 'T',
  '2*dulles airport virginia': 'R',
  '3*dulles airport virginia transport to other cities': 'R',
 },
 '25': {
  '1*Boston pops  and (salary OR manager OR conductor OR hall)': 'T',
  '2*Boston pops': 'R',
 },
 '26': {
  '1*Boston Pops': 'T',
  '2*Define: Boston Pops': 'T',
  '3*Conductor of the boston pops orchestra': 'R',
  '4*Conductor 2012 of the boston pops orchestra': 'T',
  '5*Information regarding the Boston Pops Conductor': 'T',
  '6*Information regarding the Boston Pops Manager': 'R',
 },
 '27': {
  '1*jeopardy': 'T',
  '2*jeopardy gameplay': 'T',
  '3*jeopardy video': 'R',
 },
 '28': {
  '1*"jeopardy game show"': 'T',
  '2*"jeopardy game show" history': 'R',
 },
 '29': {
  '1*jeopardy (game show)': 'T',
  '2*jeopardy (game show) wikipedia': 'T',
  '3*wikipedia jeopardy': 'T',
 },
 '30': {
  '1*churchill downs': 'T',
  '2*churchill downs 2013': 'R',
 },
 '31': {
  '1*churchill downs racing information': 'T',
  '2*churchill downs horse racing park': 'R',
  '3*"churchill downs" horse racing park': 'T',
  '4*"churchill downs" horse racing schedule': 'T',
  '5*kentucky derby museum': 'R',
  '6*churchilldowns.com': 'R',
  '7*churchilldowns': 'T',
  '8*churchilldowns seating chart': 'R',
  '9*"churchill downs" racing seating chart': 'T',
 },
 '32': {
  '1*Churchill downs schedule': 'T',
  '2*Churchill downs race schedule 2013': 'T',
  '3*Churchill downs seating': 'R',
  '4*Churchill downs Kentucky derby museum': 'R',
 },
 '33': {
  '1*general schedule pay tables': 'T',
  '2*general schedule pay tables 2013': 'R',
  '3*general schedule pay tables federal wage system': 'R',
  '4*general schedule pay tables "federal goverment"': 'R',
 },
 '34': {
  '1*internet phone services': 'T',
  '2*internet phone services review': 'R',
  '3*guide internet phone services': 'T',
  '4*voip providers': 'R',
 },
 '35': {
  '1*regular phones vs internet phones voip experiences cheapest': 'T',
  '2*internet phones voip experiences cheapest': 'T',
  '3*internet phones voip reviews': 'R',
 },
 '36': {
  '1*VOIP': 'T',
  '2*VOIP lietuva': 'R',
  '3*VOIP paslaugos lietuva': 'T',
  '4*ip telefonijos paslaugos': 'R',
  '5*ip telefonija': 'T',
  '6*ip telefonija kaunas': 'T',
  '7*ip telefonas': 'R',
  '8*ip balso telefonija': 'R',
  '9*voip telefonas': 'R',
 },
 '37': {
  '1*"State university of new york" bioinformatics': 'T',
  '2*"State university of new york"': 'R',
 },
 '38': {
  '1*SUNY colleges': 'T',
  '2*SUNY albany hospital location': 'R',
  '3*"SUNY albany hospital" location': 'T',
  '4*"SUNY albany hospital" location': 'T',
  '5*albany university hospital location': 'T',
  '6*SUNY plattsburgh athletics': 'R',
 },
 '39': {
  '1*suny colleges names': 'T',
  '2*number of suny colleges': 'R',
  '3*suny college bioinformatics degree': 'R',
  '4*map suny albany hospital': 'R',
  '5*map "albany hospital" ny': 'T',
 },
 '40': {
  '1*gun control opinions': 'T',
  '2*gun control us government': 'R',
  '3*gun control current affairs': 'R',
  '4*gun control current affairs': 'T',
  '5*gun violence us': 'R',
  '6*law center to prevent gun violence': 'R',
 },
 '41': {
  '1*obama gun control': 'T',
  '2*gun control laws obama': 'T',
 },
 '42': {
  '1*most violent gun violence events': 'T',
  '2*gun violence us campuses': 'R',
  '3*most deadly type of gun in gun violence': 'R',
 },
 '43': {
  '1*gun violence in USA': 'T',
  '2*gun violence on US college campus': 'R',
  '3*gun violence on US campus': 'T',
  '4*types of gun used in violent events': 'R',
 },
 '44': {
  '1*healty recipes': 'T',
  '2*healthy meals': 'T',
  '3*healthy nutrition for infants': 'R',
 },
 '45': {
  '1*red bull drink health concerns': 'T',
  '2*red bull drink side effects ban': 'R',
  '3*red bull ban': 'T',
 },
 '46': {
  '1*Red Bull AND health': 'T',
  '2*Red Bull': 'R',
  '3*red bull': 'T',
  '4*red bull effects': 'R',
  '5*red bull drink': 'R',
  '6*red bull ingridients': 'R',
  '7*red bull ingredients': 'T',
  '8*red bull in US': 'R',
 },
 '47': {
  '1*banned drinks': 'T',
  '2*banned food': 'R',
  '3*illegal beverages': 'R',
 },
 '48': {
  '1*patent filing': 'T',
  '2*patent filing': 'T',
  '3*patent office': 'R',
  '4*patent law': 'R',
  '5*patent law uk': 'T',
  '6*patent lawyer': 'R',
  '7*provisional patent': 'R',
 },
 '49': {
  '1*face transplant': 'T',
  '2*finished the task': 'R',
 },
 '50': {
  '1*diet exercise for fitness': 'T',
  '2*fitness wiki': 'T',
  '3*wikipedia': 'R',
  '4*paleo diet': 'R',
  '5*keto diet': 'R',
  '6*keto diet wikipedia': 'T',
  '7*exercises for fitness': 'R',
  '8*how to get fit safely': 'R',
 },
 '51': {
  '1*fitness regime': 'T',
  '2*running a half marathon': 'R',
 },
 '52': {
  '1*venture capital': 'T',
  '2*loans for entrepreneurship': 'R',
  '3*loans for entrepreneurship switzerland': 'T',
  '4*loans for business': 'T',
  '5*loans for business us government': 'T',
  '6*renting a building business sillicon valley': 'R',
  '7*renting an office sillicon valley': 'T',
 },
 '53': {
  '1*how to get a pay raise': 'T',
  '2*tips pay raise': 'T',
  '3*tips pay raise': 'T',
 },
 '54': {
  '1*preventing employee fraud in recession': 'T',
  '2*recession employee fraud': 'T',
  '3*employee fraud best practice': 'T',
  '4*"employee fraud" "best practice"': 'T',
 },
 '55': {
  '1*employee evaluation': 'T',
  '2*evaluate employees': 'T',
  '3*evaluate employees': 'T',
 },
 '56': {
  '1*events ideas students community': 'T',
  '2*events ideas student association': 'T',
 },
 '57': {
  '1*developmental milestones infants': 'T',
  '2*developmental milestones infants 0-12 months': 'T',
  '3*developmental milestones infants east asia': 'R',
  '4*developmental milestones east asia': 'T',
  '5*"developmental milestones in east asia"': 'T',
  '6*developmental milestones asian infants': 'T',
  '7*asian infants': 'T',
  '8*asian infants milestones': 'T',
  '9*asian infants development': 'T',
  '10*asian babies development': 'T',
  '11*developmental milestones asia': 'T',
  '12*are developmental milestones universal': 'R',
  '13*asian developmental milestones': 'R',
  '14*chinese infant developmental milestones': 'R',
  '15*chinese infant milestones': 'T',
  '16*infant milestones variations': 'R',
  '17*infant milestones cultural': 'T',
  '18*infant milestones differences': 'T',
  '19*asian children milestones': 'R',
 },
 '58': {
  '1*policies for addressing economic problems in europe': 'T',
  '2*\'EUROPEAN UNION" "ECONOMIC CRISIS"': 'R',
  '3*\'EUROPEAN UNION" "ECONOMIC CRISIS" greece': 'R',
  '4*\'EUROPEAN UNION" "ECONOMIC CRISIS" portugal': 'R',
  '5*\'EUROPEAN UNION" "ECONOMIC CRISIS" spain': 'R',
 },
 '59': {
  '1*eurozone crisis responses': 'T',
  '2*eurozone crisis leader actions': 'R',
 },
 '60': {
  '1*eurozone portugal leader actions': 'T',
  '2*eurozone spain leader actions': 'R',
  '3*spain spanish leader crisis action': 'T',
  '4*ireland spanish leader crisis action': 'R',
  '5*ireland irish leader crisis action': 'T',
  '6*piigs leader crisis action': 'R',
  '7*cyprus leader crisis action': 'R',
 },
 '61': {
  '1*round-trip v road-trip': 'T',
  '2*round-trip advantages versus road-trip': 'R',
  '3*round-trip enjoyable versus road-trip': 'T',
  '4*round-trip enjoyable versus road-trip boring?': 'T',
 },
 '62': {
  '1*road trip': 'T',
  '2*best road trips': 'R',
  '3*best worst road trips': 'R',
  '4*romantic road trips': 'R',
  '5*enjoyable boring road trip': 'R',
  '6*enjoyable boring getaways': 'T',
  '7*best getaways': 'R',
 },
 '63': {
  '1*good internet phone services': 'T',
  '2*internet phone': 'T',
  '3*what\'s good about internet phoning': 'R',
  '4*"what\'s good about internet phoning"': 'T',
  '5*phone': 'R',
  '6*phone internet': 'R',
  '7*phone internet providers': 'T',
  '8*good Voip': 'R',
  '9*Voip reviews': 'T',
 },
 '64': {
  '1*why is internet phone service great': 'T',
  '2*why internet phone service great': 'T',
 },
 '65': {
  '1*gun control': 'T',
  '2*gun control laws': 'R',
  '3*gun control outcomes': 'R',
  '4*ban guns': 'R',
 },
 '66': {
  '1*gun control': 'T',
  '2*gun control violence': 'R',
  '3*does gun control reduce gun violence': 'R',
 },
 '67': {
  '1*god existence': 'T',
  '2*naturalism': 'R',
  '3*naturalism theory': 'T',
  '4*naturalism theism': 'T',
 },
 '68': {
  '1*US healthcare social security worker': 'T',
  '2*US healthcare system': 'T',
  '3*us healthcare for employed': 'T',
  '4*how does healthcare work in the USA for employed people?': 'T',
 },
 '69': {
  '1*malaria impact on economy africa': 'T',
  '2*malaria economy africa': 'T',
  '3*malaria economy': 'T',
  '4*malaria donations': 'R',
 },
 '70': {
  '1*HIV Africa charity medicine': 'T',
  '2*HIV Africa charity': 'T',
  '3*HIV Africa charity donate': 'R',
  '4*AIDS Africa charity donate': 'T',
  '5*malaria Africa charity donate': 'T',
 },
 '71': {
  '1*teachers evaluation': 'T',
  '2*teachers evaluation by students': 'R',
  '3*teachers evaluation students peers': 'R',
  '4*teachers evaluation peers': 'R',
  '5*teachers evaluation peers students': 'R',
  '6*teachers evaluation by students': 'R',
  '7*teachers evaluation': 'R',
  '8*teachers evaluation wikipedia': 'T',
  '9*teachers assement': 'T',
  '10*teachers evaluation': 'T',
  '11*teachers excellence': 'T',
  '12*teache assement wikipedia': 'T',
 },
 '72': {
  '1*infants development culture': 'T',
  '2*infant development "cultural effects"': 'T',
  '3*infant OR child development intitle:culture': 'T',
  '4*infant OR child development milestones': 'R',
  '5*infant OR child development milestones research': 'T',
  '6*infant OR child "development milestones" +research': 'T',
  '7*infant OR child "development milestones" site:ac.uk': 'T',
  '8*Do infants age 0-12 months experience different developmental milestones depending on culture': 'R',
  '9*culture OR race infant OR child development stages OR milestones': 'T',
  '10*research culture OR race infant OR child development stages OR milestones': 'T',
  '11*infant OR child development "effect of culture"': 'T',
  '12*infant OR child development "cultural differences"': 'T',
  '13*"child development" "cultural differences"': 'T',
 },
 '73': {
  '1*babies development "cultural differences"': 'T',
  '2*infant different developmental milestones depending on culture': 'T',
  '3*developmental milestones infants "cultural differences"': 'T',
 },
 '74': {
  '1*infant development cultural differences': 'T',
  '2*infant development western eastern cultures': 'R',
  '3*infant development milestone cultural effects': 'T',
  '4*infant development milestone "cultural differences"': 'T',
  '5*infant development milestone "cultural competence': 'T',
  '6*infant development milestone developed and third world countries': 'R',
 },
 '75': {
  '1*legality alcohol marijuana': 'T',
  '2*legality alcohol marijuana history': 'T',
  '3*legality alcohol history': 'T',
  '4*legality alcohol history maijuana': 'T',
  '5*legality alcohol history marijuana': 'T',
  '6*why is marijuana illegal?': 'R',
  '7*is marijuana worse for your health than alcohol?': 'R',
 },
 '76': {
  '1*phone plan': 'T',
  '2*"cell phone plan"': 'T',
  '3*"cell phone plan :.uk"': 'R',
 },
 '77': {
  '1*tax junk food benefits': 'T',
  '2*tax junk food benefits un': 'R',
  '3*tax junk food benefits UN evidence': 'T',
  '4*high calorie food tax evidence based': 'R',
  '5*high calorie snack tax evidence based': 'T',
  '6*government intervention tax "junk food"': 'T',
 },
 '78': {
  '1*advantages of junk food': 'T',
  '2*tax on junk food': 'R',
 },
 '79': {
  '1*food tax': 'T',
  '2*food ban': 'R',
 },
 '80': {
  '1*the benefits of exploration space': 'T',
  '2*the benefits of "exploration space"': 'T',
 },
 '81': {
  '1*women  and minorities percentage setting': 'T',
  '2*should numbers of women and minorities in workplace be contolled': 'R',
 },
 '82': {
  '1*jobs from business phds': 'T',
  '2*business phd': 'R',
 },
 '83': {
  '1*phd business jobs': 'T',
  '2*phd business salaries': 'R',
  '3*business phd funding': 'R',
  '4*business phd vs masters': 'R',
  '5*business phd duration': 'R',
  '6*business phd income': 'R',
 },
 '84': {
  '1*travel spots room prices': 'T',
  '2*travel spots room prices hawaii': 'R',
 },
 '85': {
  '1*Secondhand camera shop': 'T',
  '2*Travel information Los Angeles': 'R',
  '3*Local Travel information Los Angeles': 'T',
  '4*Travel information Los Angeles': 'T',
 },
 '86': {
  '1*New York City': 'T',
  '2*Chicago': 'R',
  '3*Washington DC': 'R',
 },
 '87': {
  '1*best us destinations': 'T',
  '2*distance new york boston': 'R',
  '3*maps.bing.com': 'R',
  '4*maps': 'T',
  '5*bing maps': 'T',
  '6*hartford tourism': 'R',
  '7*bing maps': 'R',
  '8*hartford visitors': 'T',
  '9*hartford connecticut tourism': 'T',
  '10*hartford boston travel': 'R',
  '11*boston tourism': 'T',
  '12*nyc tourism': 'R',
  '13*philadelphia nyc distance': 'R',
  '14*bing maps': 'R',
  '15*philadelphia washington dc distance': 'T',
  '16*bing maps': 'R',
  '17*philadelphia tourism': 'T',
  '18*washington dc tourism': 'R',
  '19*philadelphia nyc travel': 'R',
  '20*philadelphia nyc train': 'T',
  '21*philadelphia nyc bus': 'T',
 },
 '88': {
  '1*scooter comparison': 'T',
 },
 '89': {
  '1*ron howard filmography': 'T',
 },
 '90': {
  '1*Ron Howard, movies': 'T',
 },
 '91': {
  '1*paralegal career': 'T',
 },
 '92': {
  '1*weatherstripping': 'T',
 },
 '93': {
  '1*+(Black OR african-american) history month events': 'T',
 },
 '94': {
  '1*Black history month': 'T',
 },
 '95': {
  '1*comparison hotels new york city': 'T',
 },
 '96': {
  '1*American Coins': 'T',
 },
 '97': {
  '1*methods and programs for quitting smoking': 'T',
 },
 '98': {
  '1*quit quitting smoking': 'T',
 },
 '99': {
  '1*Kansas attractions': 'T',
 },
 '100': {
  '1*further education for high school teachers': 'T',
 },
 '101': {
  '1*higher degrees for high school teacher': 'T',
 },
 '102': {
  '1*jp morgan chase data centers': 'T',
 },
 '103': {
  '1*"history of face transplants"': 'T',
 },
 '104': {
  '1*AMT tax IRS': 'T',
 },
 '105': {
  '1*uss abraham lincoln': 'T',
 },
 '106': {
  '1*guide dulles airport': 'T',
 },
 '107': {
  '1*Dulles airport': 'T',
 },
 '108': {
  '1*Boston pops official website': 'T',
 },
 '109': {
  '1*GS pay tables': 'T',
 },
 '110': {
  '1*Vanuatu': 'T',
 },
 '111': {
  '1*healthy nutrition, children, pregnant women, government programes': 'T',
 },
 '112': {
  '1*patent application': 'T',
 },
 '113': {
  '1*face transplants': 'T',
 },
 '114': {
  '1*face transplants': 'T',
 },
 '115': {
  '1*advice for technology start-up': 'T',
 },
 '116': {
  '1*how to succeed in new venture': 'T',
 },
 '117': {
  '1*innovation': 'T',
 },
 '118': {
  '1*evaluating employees': 'T',
 },
 '119': {
  '1*eurozone crisis economic actions': 'T',
 },
 '120': {
  '1*Philadelphia attractions': 'T',
 },
 '121': {
  '1*Philadelphia tourist attractions': 'T',
 },
 '122': {
  '1*tour bus': 'T',
 },
 '123': {
  '1*legality gun control': 'T',
 },
 '124': {
  '1*god does not exist': 'T',
 },
 '125': {
  '1*existence god naturalism theory': 'T',
 },
 '126': {
  '1*hiv aids prevention cure charities in africa': 'T',
 },
 '127': {
  '1*teacher evaluation peer versus students': 'T',
 },
 '128': {
  '1*EU economic indicators': 'T',
 },
 '129': {
  '1*What are the effects of the ongoing Eurozone crisis on national economic indicators such as unemployment, GDP, public debt, etc': 'T',
 },
 '130': {
  '1*Jp Morgan Chase': 'T',
 },
 '131': {
  '1*us space exploration costs': 'T',
 },
 '132': {
  '1*(euro OR eurozone) crisis': 'T',
 },
 '133': {
  '1*eurozone crisis': 'T',
 }
}
